site_name: SMA - BDI em Sistema Presa-Predador
site_url: https://unbsma2025-2.github.io/2025.2_G4_SMA_BDIemSistemaPresaPredador/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Início: index.md
  - Investigando: investigando.md

extra_css:
  - assets/extra.css
